services:
  db:
    image: postgres:16-alpine 
    container_name: staff_postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: StaffSystem
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "8080:8080"

  web:
    build:
      context: ..
      dockerfile: Dockerfile
    container_name: staff_web_app
    restart: always
    ports:
      - "8080:80"
    environment:
      ConnectionStrings__DefaultConnection: Host=db;Port=5432;Database=StaffSystem;Username=postgres;Password=password;
    depends_on:
      - db
    
volumes:
  postgres_data: